const europeGroups = [[], [], [], [], [], [], [], [], [], [], []]
const africaGroups = [[], [], [], [], [], [], [], [], [], []]
const asiaGroups = [[], [], [], [], [], [], [], []]
const southAmericaGroups = [[], []]
const northAmericaGroups = [[], [], [], [], [], [], []]
const oceaniaGroups = [[]]

const qualsState = {
    europeGroups,
    africaGroups,
    asiaGroups,
    southAmericaGroups,
    northAmericaGroups,
    oceaniaGroups
}


export const qualsReducer = (state = qualsState, action) => {
    switch(action.type) {
        case "DRAW_EUROPE1": 
            return {...state, europeGroups: [[...state.europeGroups[0], action.payload[0] ? action.payload[0] : []], [...state.europeGroups[1], action.payload[1] ? action.payload[1] : []], [...state.europeGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.europeGroups[3], action.payload[3] ? action.payload[3] : []], [...state.europeGroups[4], action.payload[4] ? action.payload[4] : []], [...state.europeGroups[5], action.payload[5] ? action.payload[5] : []], [...state.europeGroups[6], action.payload[6] ? action.payload[6] : []], [...state.europeGroups[7], action.payload[7] ? action.payload[7] : []], [...state.europeGroups[8], action.payload[8] ? action.payload[8] : []],  [...state.europeGroups[9], action.payload[9] ? action.payload[9] : [] ], [...state.europeGroups[10], action.payload[10] ? action.payload[10] : []]]}
        case "DRAW_EUROPE2": 
            return {...state, europeGroups: [[...state.europeGroups[0], action.payload[0] ? action.payload[0] : []], [...state.europeGroups[1], action.payload[1] ? action.payload[1] : []], [...state.europeGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.europeGroups[3], action.payload[3] ? action.payload[3] : []], [...state.europeGroups[4], action.payload[4] ? action.payload[4] : []], [...state.europeGroups[5], action.payload[5] ? action.payload[5] : []], [...state.europeGroups[6], action.payload[6] ? action.payload[6] : []], [...state.europeGroups[7], action.payload[7] ? action.payload[7] : []], [...state.europeGroups[8], action.payload[8] ? action.payload[8] : []],  [...state.europeGroups[9], action.payload[9] ? action.payload[9] : [] ], [...state.europeGroups[10], action.payload[10] ? action.payload[10] : []]]}
        case "DRAW_EUROPE3":
            return {...state, europeGroups: [[...state.europeGroups[0], action.payload[0] ? action.payload[0] : []], [...state.europeGroups[1], action.payload[1] ? action.payload[1] : []], [...state.europeGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.europeGroups[3], action.payload[3] ? action.payload[3] : []], [...state.europeGroups[4], action.payload[4] ? action.payload[4] : []], [...state.europeGroups[5], action.payload[5] ? action.payload[5] : []], [...state.europeGroups[6], action.payload[6] ? action.payload[6] : []], [...state.europeGroups[7], action.payload[7] ? action.payload[7] : []], [...state.europeGroups[8], action.payload[8] ? action.payload[8] : []],  [...state.europeGroups[9], action.payload[9] ? action.payload[9] : [] ], [...state.europeGroups[10], action.payload[10] ? action.payload[10] : []]]}
        case "DRAW_EUROPE4":
            return {...state, europeGroups: [[...state.europeGroups[0], action.payload[0] ? action.payload[0] : []], [...state.europeGroups[1], action.payload[1] ? action.payload[1] : []], [...state.europeGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.europeGroups[3], action.payload[3] ? action.payload[3] : []], [...state.europeGroups[4], action.payload[4] ? action.payload[4] : []], [...state.europeGroups[5], action.payload[5] ? action.payload[5] : []], [...state.europeGroups[6], action.payload[6] ? action.payload[6] : []], [...state.europeGroups[7], action.payload[7] ? action.payload[7] : []], [...state.europeGroups[8], action.payload[8] ? action.payload[8] : []],  [...state.europeGroups[9], action.payload[9] ? action.payload[9] : [] ], [...state.europeGroups[10], action.payload[10] ? action.payload[10] : []]]}
        case "DRAW_EUROPE5":
            return {...state, europeGroups: [[...state.europeGroups[0], action.payload[0] ? action.payload[0] : []], [...state.europeGroups[1], action.payload[1] ? action.payload[1] : []], [...state.europeGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.europeGroups[3], action.payload[3] ? action.payload[3] : []], [...state.europeGroups[4], action.payload[4] ? action.payload[4] : []], [...state.europeGroups[5], action.payload[5] ? action.payload[5] : []], [...state.europeGroups[6], action.payload[6] ? action.payload[6] : []], [...state.europeGroups[7], action.payload[7] ? action.payload[7] : []], [...state.europeGroups[8], action.payload[8] ? action.payload[8] : []],  [...state.europeGroups[9], action.payload[9] ? action.payload[9] : [] ], [...state.europeGroups[10], action.payload[10] ? action.payload[10] : []]]}       
        case "DRAW_SOUTH_AMERICA1":
            return {...state, southAmericaGroups: [[...state.southAmericaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.southAmericaGroups[1], action.payload[1] ? action.payload[1] : []]]}
        case "DRAW_SOUTH_AMERICA2":
            return {...state, southAmericaGroups: [[...state.southAmericaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.southAmericaGroups[1], action.payload[1] ? action.payload[1] : []]]}
        case "DRAW_SOUTH_AMERICA3":
            return {...state, southAmericaGroups: [[...state.southAmericaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.southAmericaGroups[1], action.payload[1] ? action.payload[1] : []]]}
        case "DRAW_SOUTH_AMERICA4":
            return {...state, southAmericaGroups: [[...state.southAmericaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.southAmericaGroups[1], action.payload[1] ? action.payload[1] : []]]}
        case "DRAW_SOUTH_AMERICA5":
            return {...state, southAmericaGroups: [[...state.southAmericaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.southAmericaGroups[1], action.payload[1] ? action.payload[1] : []]]}
        case "DRAW_NORTH_AMERICA1": 
            return {...state, northAmericaGroups: [[...state.northAmericaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.northAmericaGroups[1], action.payload[1] ? action.payload[1] : []], [...state.northAmericaGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.northAmericaGroups[3], action.payload[3] ? action.payload[3] : []], [...state.northAmericaGroups[4], action.payload[4] ? action.payload[4] : []], [...state.northAmericaGroups[5], action.payload[5] ? action.payload[5] : []], [...state.northAmericaGroups[6], action.payload[6] ? action.payload[6] : []]]}
        case "DRAW_NORTH_AMERICA2": 
            return {...state, northAmericaGroups: [[...state.northAmericaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.northAmericaGroups[1], action.payload[1] ? action.payload[1] : []], [...state.northAmericaGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.northAmericaGroups[3], action.payload[3] ? action.payload[3] : []], [...state.northAmericaGroups[4], action.payload[4] ? action.payload[4] : []], [...state.northAmericaGroups[5], action.payload[5] ? action.payload[5] : []], [...state.northAmericaGroups[6], action.payload[6] ? action.payload[6] : []]]}
        case "DRAW_NORTH_AMERICA3":
            return {...state, northAmericaGroups: [[...state.northAmericaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.northAmericaGroups[1], action.payload[1] ? action.payload[1] : []], [...state.northAmericaGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.northAmericaGroups[3], action.payload[3] ? action.payload[3] : []], [...state.northAmericaGroups[4], action.payload[4] ? action.payload[4] : []], [...state.northAmericaGroups[5], action.payload[5] ? action.payload[5] : []], [...state.northAmericaGroups[6], action.payload[6] ? action.payload[6] : []]]}
        case "DRAW_NORTH_AMERICA4":
            return {...state, northAmericaGroups: [[...state.northAmericaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.northAmericaGroups[1], action.payload[1] ? action.payload[1] : []], [...state.northAmericaGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.northAmericaGroups[3], action.payload[3] ? action.payload[3] : []], [...state.northAmericaGroups[4], action.payload[4] ? action.payload[4] : []], [...state.northAmericaGroups[5], action.payload[5] ? action.payload[5] : []], [...state.northAmericaGroups[6], action.payload[6] ? action.payload[6] : []]]}
        case "DRAW_NORTH_AMERICA5":
            return {...state, northAmericaGroups: [[...state.northAmericaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.northAmericaGroups[1], action.payload[1] ? action.payload[1] : []], [...state.northAmericaGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.northAmericaGroups[3], action.payload[3] ? action.payload[3] : []], [...state.northAmericaGroups[4], action.payload[4] ? action.payload[4] : []], [...state.northAmericaGroups[5], action.payload[5] ? action.payload[5] : []], [...state.northAmericaGroups[6], action.payload[6] ? action.payload[6] : []]]}       
        case "DRAW_AFRICA1": 
            return {...state, africaGroups: [[...state.africaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.africaGroups[1], action.payload[1] ? action.payload[1] : []], [...state.africaGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.africaGroups[3], action.payload[3] ? action.payload[3] : []], [...state.africaGroups[4], action.payload[4] ? action.payload[4] : []], [...state.africaGroups[5], action.payload[5] ? action.payload[5] : []], [...state.africaGroups[6], action.payload[6] ? action.payload[6] : []], [...state.africaGroups[7], action.payload[7] ? action.payload[7] : []], [...state.africaGroups[8], action.payload[8] ? action.payload[8] : []], [...state.africaGroups[9], action.payload[9] ? action.payload[9] : []]]}
        case "DRAW_AFRICA2": 
            return {...state, africaGroups: [[...state.africaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.africaGroups[1], action.payload[1] ? action.payload[1] : []], [...state.africaGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.africaGroups[3], action.payload[3] ? action.payload[3] : []], [...state.africaGroups[4], action.payload[4] ? action.payload[4] : []], [...state.africaGroups[5], action.payload[5] ? action.payload[5] : []], [...state.africaGroups[6], action.payload[6] ? action.payload[6] : []], [...state.africaGroups[7], action.payload[7] ? action.payload[7] : []], [...state.africaGroups[8], action.payload[8] ? action.payload[8] : []], [...state.africaGroups[9], action.payload[9] ? action.payload[9] : []]]}
        case "DRAW_AFRICA3":
            return {...state, africaGroups: [[...state.africaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.africaGroups[1], action.payload[1] ? action.payload[1] : []], [...state.africaGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.africaGroups[3], action.payload[3] ? action.payload[3] : []], [...state.africaGroups[4], action.payload[4] ? action.payload[4] : []], [...state.africaGroups[5], action.payload[5] ? action.payload[5] : []], [...state.africaGroups[6], action.payload[6] ? action.payload[6] : []], [...state.africaGroups[7], action.payload[7] ? action.payload[7] : []], [...state.africaGroups[8], action.payload[8] ? action.payload[8] : []], [...state.africaGroups[9], action.payload[9] ? action.payload[9] : []]]}
        case "DRAW_AFRICA4":
            return {...state, africaGroups: [[...state.africaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.africaGroups[1], action.payload[1] ? action.payload[1] : []], [...state.africaGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.africaGroups[3], action.payload[3] ? action.payload[3] : []], [...state.africaGroups[4], action.payload[4] ? action.payload[4] : []], [...state.africaGroups[5], action.payload[5] ? action.payload[5] : []], [...state.africaGroups[6], action.payload[6] ? action.payload[6] : []], [...state.africaGroups[7], action.payload[7] ? action.payload[7] : []], [...state.africaGroups[8], action.payload[8] ? action.payload[8] : []], [...state.africaGroups[9], action.payload[9] ? action.payload[9] : []]]}
        case "DRAW_AFRICA5":
            return {...state, africaGroups: [[...state.africaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.africaGroups[1], action.payload[1] ? action.payload[1] : []], [...state.africaGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.africaGroups[3], action.payload[3] ? action.payload[3] : []], [...state.africaGroups[4], action.payload[4] ? action.payload[4] : []], [...state.africaGroups[5], action.payload[5] ? action.payload[5] : []], [...state.africaGroups[6], action.payload[6] ? action.payload[6] : []], [...state.africaGroups[7], action.payload[7] ? action.payload[7] : []], [...state.africaGroups[8], action.payload[8] ? action.payload[8] : []], [...state.africaGroups[9], action.payload[9] ? action.payload[9] : []]]}       
        case "DRAW_ASIA1": 
            return {...state, asiaGroups: [[...state.asiaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.asiaGroups[1], action.payload[1] ? action.payload[1] : []], [...state.asiaGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.asiaGroups[3], action.payload[3] ? action.payload[3] : []], [...state.asiaGroups[4], action.payload[4] ? action.payload[4] : []], [...state.asiaGroups[5], action.payload[5] ? action.payload[5] : []], [...state.asiaGroups[6], action.payload[6] ? action.payload[6] : []], [...state.asiaGroups[7], action.payload[7] ? action.payload[7] : []]]}
        case "DRAW_ASIA2": 
            return {...state, asiaGroups: [[...state.asiaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.asiaGroups[1], action.payload[1] ? action.payload[1] : []], [...state.asiaGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.asiaGroups[3], action.payload[3] ? action.payload[3] : []], [...state.asiaGroups[4], action.payload[4] ? action.payload[4] : []], [...state.asiaGroups[5], action.payload[5] ? action.payload[5] : []], [...state.asiaGroups[6], action.payload[6] ? action.payload[6] : []], [...state.asiaGroups[7], action.payload[7] ? action.payload[7] : []]]}
        case "DRAW_ASIA3":
            return {...state, asiaGroups: [[...state.asiaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.asiaGroups[1], action.payload[1] ? action.payload[1] : []], [...state.asiaGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.asiaGroups[3], action.payload[3] ? action.payload[3] : []], [...state.asiaGroups[4], action.payload[4] ? action.payload[4] : []], [...state.asiaGroups[5], action.payload[5] ? action.payload[5] : []], [...state.asiaGroups[6], action.payload[6] ? action.payload[6] : []], [...state.asiaGroups[7], action.payload[7] ? action.payload[7] : []]]}
        case "DRAW_ASIA4":
            return {...state, asiaGroups: [[...state.asiaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.asiaGroups[1], action.payload[1] ? action.payload[1] : []], [...state.asiaGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.asiaGroups[3], action.payload[3] ? action.payload[3] : []], [...state.asiaGroups[4], action.payload[4] ? action.payload[4] : []], [...state.asiaGroups[5], action.payload[5] ? action.payload[5] : []], [...state.asiaGroups[6], action.payload[6] ? action.payload[6] : []], [...state.asiaGroups[7], action.payload[7] ? action.payload[7] : []]]}
        case "DRAW_ASIA5":
            return {...state, asiaGroups: [[...state.asiaGroups[0], action.payload[0] ? action.payload[0] : []], [...state.asiaGroups[1], action.payload[1] ? action.payload[1] : []], [...state.asiaGroups[2], action.payload[2] ? action.payload[2] : []],  [...state.asiaGroups[3], action.payload[3] ? action.payload[3] : []], [...state.asiaGroups[4], action.payload[4] ? action.payload[4] : []], [...state.asiaGroups[5], action.payload[5] ? action.payload[5] : []], [...state.asiaGroups[6], action.payload[6] ? action.payload[6] : []], [...state.asiaGroups[7], action.payload[7] ? action.payload[7] : []]]}
        case "DRAW_OCEANIA1": 
            return {...state, oceaniaGroups: [[...state.oceaniaGroups[0], action.payload[0] ? action.payload[0] : []]]}
        case "DRAW_OCEANIA2": 
            return {...state, oceaniaGroups: [[...state.oceaniaGroups[0], action.payload[0] ? action.payload[0] : []]]}
        case "DRAW_OCEANIA3": 
            return {...state, oceaniaGroups: [[...state.oceaniaGroups[0], action.payload[0] ? action.payload[0] : []]]}
        case "DRAW_OCEANIA4": 
            return {...state, oceaniaGroups: [[...state.oceaniaGroups[0], action.payload[0] ? action.payload[0] : []]]}
        case "DRAW_OCEANIA5": 
            return {...state, oceaniaGroups: [[...state.oceaniaGroups[0], action.payload[0] ? action.payload[0] : []]]}
        default: 
            return state    
    }
}