import { shedule } from "../data/shedule";

const ue_group1 = shedule;
const ue_group2 = shedule;
const ue_group3 = shedule;
const ue_group4 = shedule;
const ue_group5 = shedule;
const ue_group6 = shedule;
const ue_group7 = shedule;
const ue_group8 = shedule;
const ue_group9 = shedule;
const ue_group10 = shedule;
const ue_group11 = shedule;
const as_group1 = shedule;
const as_group2 = shedule;
const as_group3 = shedule;
const as_group4 = shedule;
const as_group5 = shedule;
const as_group6 = shedule;
const as_group7 = shedule;
const as_group8 = shedule;
const sa_group1 = shedule;
const sa_group2 = shedule;
const oc_group1 = shedule;
const af_group1 = shedule;
const af_group2 = shedule;
const af_group3 = shedule;
const af_group4 = shedule;
const af_group5 = shedule;
const af_group6 = shedule;
const af_group7 = shedule;
const af_group8 = shedule;
const af_group9 = shedule;
const af_group10 = shedule;
const na_group1 = shedule;
const na_group2 = shedule;
const na_group3 = shedule;
const na_group4 = shedule;
const na_group5 = shedule;
const na_group6 = shedule;
const na_group7 = shedule;

const sheduleState = {
  sa_group1,
  sa_group2,
  ue_group1,
  ue_group2,
  ue_group3,
  ue_group4,
  ue_group5,
  ue_group6,
  ue_group7,
  ue_group8,
  ue_group9,
  ue_group10,
  ue_group11,
  as_group1,
  as_group2,
  as_group3,
  as_group4,
  as_group5,
  as_group6,
  as_group7,
  as_group8,
  oc_group1,
  af_group1,
  af_group2,
  af_group3,
  af_group4,
  af_group5,
  af_group6,
  af_group7,
  af_group8,
  af_group9,
  af_group10,
  na_group1,
  na_group2,
  na_group3,
  na_group4,
  na_group5,
  na_group6,
  na_group7,
};

export const sheduleReducer = (state = sheduleState, action) => {
  const ans = action.payload;
  const game = (game) => {
    if (
      game.teamone.id === ans.teamone.id &&
      game.teamtwo.id === ans.teamtwo.id
    ) {
      return {
        ...game,
        endGame: ans.endGame,
        scOne: ans.scOne,
        scTwo: ans.scTwo,
      };
    }
    return game;
  };
  switch (action.type) {
    case "SA_GROUP1":
      return {
        ...state,
        sa_group1: [
          { ...state.sa_group1[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.sa_group1[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.sa_group1[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.sa_group1[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.sa_group1[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.sa_group1[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.sa_group1[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.sa_group1[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.sa_group1[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.sa_group1[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.sa_group1[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.sa_group1[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.sa_group1[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.sa_group1[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.sa_group1[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.sa_group1[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.sa_group1[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.sa_group1[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.sa_group1[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.sa_group1[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "SA_GROUP2":
      return {
        ...state,
        sa_group2: [
          { ...state.sa_group2[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.sa_group2[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.sa_group2[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.sa_group2[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.sa_group2[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.sa_group2[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.sa_group2[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.sa_group2[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.sa_group2[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.sa_group2[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.sa_group2[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.sa_group2[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.sa_group2[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.sa_group2[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.sa_group2[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.sa_group2[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.sa_group2[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.sa_group2[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.sa_group2[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.sa_group2[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    
    case "EU_GROUP1":
      return {
        ...state,
        ue_group1: [
          { ...state.ue_group1[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.ue_group1[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.ue_group1[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.ue_group1[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.ue_group1[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.ue_group1[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.ue_group1[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.ue_group1[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.ue_group1[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.ue_group1[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.ue_group1[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.ue_group1[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.ue_group1[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.ue_group1[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.ue_group1[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.ue_group1[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.ue_group1[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.ue_group1[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.ue_group1[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.ue_group1[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "EU_GROUP2":
      return {
        ...state,
        ue_group2: [
          { ...state.ue_group2[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.ue_group2[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.ue_group2[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.ue_group2[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.ue_group2[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.ue_group2[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.ue_group2[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.ue_group2[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.ue_group2[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.ue_group2[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.ue_group2[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.ue_group2[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.ue_group2[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.ue_group2[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.ue_group2[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.ue_group2[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.ue_group2[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.ue_group2[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.ue_group2[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.ue_group2[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "EU_GROUP3":
      return {
        ...state,
        ue_group3: [
          { ...state.ue_group3[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.ue_group3[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.ue_group3[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.ue_group3[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.ue_group3[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.ue_group3[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.ue_group3[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.ue_group3[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.ue_group3[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.ue_group3[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.ue_group3[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.ue_group3[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.ue_group3[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.ue_group3[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.ue_group3[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.ue_group3[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.ue_group3[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.ue_group3[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.ue_group3[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.ue_group3[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "EU_GROUP4":
      return {
        ...state,
        ue_group4: [
          { ...state.ue_group4[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.ue_group4[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.ue_group4[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.ue_group4[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.ue_group4[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.ue_group4[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.ue_group4[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.ue_group4[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.ue_group4[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.ue_group4[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.ue_group4[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.ue_group4[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.ue_group4[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.ue_group4[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.ue_group4[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.ue_group4[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.ue_group4[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.ue_group4[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.ue_group4[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.ue_group4[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "EU_GROUP5":
      return {
        ...state,
        ue_group5: [
          { ...state.ue_group5[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.ue_group5[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.ue_group5[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.ue_group5[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.ue_group5[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.ue_group5[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.ue_group5[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.ue_group5[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.ue_group5[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.ue_group5[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.ue_group5[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.ue_group5[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.ue_group5[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.ue_group5[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.ue_group5[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.ue_group5[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.ue_group5[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.ue_group5[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.ue_group5[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.ue_group5[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "EU_GROUP6":
      return {
        ...state,
        ue_group6: [
          { ...state.ue_group6[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.ue_group6[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.ue_group6[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.ue_group6[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.ue_group6[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.ue_group6[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.ue_group6[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.ue_group6[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.ue_group6[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.ue_group6[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.ue_group6[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.ue_group6[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.ue_group6[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.ue_group6[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.ue_group6[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.ue_group6[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.ue_group6[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.ue_group6[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.ue_group6[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.ue_group6[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "EU_GROUP7":
      return {
        ...state,
        ue_group7: [
          { ...state.ue_group7[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.ue_group7[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.ue_group7[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.ue_group7[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.ue_group7[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.ue_group7[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.ue_group7[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.ue_group7[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.ue_group7[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.ue_group7[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.ue_group7[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.ue_group7[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.ue_group7[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.ue_group7[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.ue_group7[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.ue_group7[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.ue_group7[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.ue_group7[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.ue_group7[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.ue_group7[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "EU_GROUP8":
      return {
        ...state,
        ue_group8: [
          { ...state.ue_group8[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.ue_group8[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.ue_group8[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.ue_group8[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.ue_group8[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.ue_group8[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.ue_group8[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.ue_group8[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.ue_group8[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.ue_group8[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.ue_group8[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.ue_group8[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.ue_group8[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.ue_group8[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.ue_group8[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.ue_group8[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.ue_group8[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.ue_group8[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.ue_group8[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.ue_group8[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "EU_GROUP9":
      return {
        ...state,
        ue_group9: [
          { ...state.ue_group9[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.ue_group9[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.ue_group9[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.ue_group9[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.ue_group9[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.ue_group9[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.ue_group9[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.ue_group9[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.ue_group9[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.ue_group9[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.ue_group9[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.ue_group9[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.ue_group9[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.ue_group9[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.ue_group9[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.ue_group9[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.ue_group9[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.ue_group9[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.ue_group9[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.ue_group9[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "EU_GROUP10":
      return {
        ...state,
        ue_group10: [
          { ...state.ue_group10[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.ue_group10[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.ue_group10[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.ue_group10[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.ue_group10[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.ue_group10[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.ue_group10[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.ue_group10[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.ue_group10[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.ue_group10[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.ue_group10[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.ue_group10[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.ue_group10[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.ue_group10[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.ue_group10[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.ue_group10[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.ue_group10[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.ue_group10[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.ue_group10[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.ue_group10[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "EU_GROUP11":
      return {
        ...state,
        ue_group11: [
          { ...state.ue_group11[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.ue_group11[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.ue_group11[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.ue_group11[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.ue_group11[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.ue_group11[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.ue_group11[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.ue_group11[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.ue_group11[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.ue_group11[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.ue_group11[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.ue_group11[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.ue_group11[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.ue_group11[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.ue_group11[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.ue_group11[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.ue_group11[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.ue_group11[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.ue_group11[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.ue_group11[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };

    case "AS_GROUP1":
      return {
        ...state,
        as_group1: [
          { ...state.as_group1[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.as_group1[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.as_group1[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.as_group1[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.as_group1[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.as_group1[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.as_group1[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.as_group1[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.as_group1[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.as_group1[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.as_group1[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.as_group1[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.as_group1[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.as_group1[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.as_group1[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.as_group1[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.as_group1[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.as_group1[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.as_group1[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.as_group1[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "AS_GROUP2":
      return {
        ...state,
        as_group2: [
          { ...state.as_group2[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.as_group2[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.as_group2[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.as_group2[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.as_group2[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.as_group2[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.as_group2[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.as_group2[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.as_group2[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.as_group2[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.as_group2[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.as_group2[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.as_group2[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.as_group2[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.as_group2[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.as_group2[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.as_group2[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.as_group2[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.as_group2[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.as_group2[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "AS_GROUP3":
      return {
        ...state,
        as_group3: [
          { ...state.as_group3[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.as_group3[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.as_group3[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.as_group3[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.as_group3[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.as_group3[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.as_group3[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.as_group3[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.as_group3[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.as_group3[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.as_group3[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.as_group3[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.as_group3[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.as_group3[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.as_group3[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.as_group3[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.as_group3[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.as_group3[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.as_group3[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.as_group3[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "AS_GROUP4":
      return {
        ...state,
        as_group4: [
          { ...state.as_group4[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.as_group4[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.as_group4[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.as_group4[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.as_group4[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.as_group4[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.as_group4[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.as_group4[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.as_group4[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.as_group4[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.as_group4[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.as_group4[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.as_group4[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.as_group4[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.as_group4[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.as_group4[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.as_group4[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.as_group4[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.as_group4[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.as_group4[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "AS_GROUP5":
      return {
        ...state,
        as_group5: [
          { ...state.as_group5[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.as_group5[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.as_group5[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.as_group5[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.as_group5[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.as_group5[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.as_group5[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.as_group5[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.as_group5[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.as_group5[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.as_group5[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.as_group5[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.as_group5[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.as_group5[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.as_group5[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.as_group5[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.as_group5[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.as_group5[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.as_group5[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.as_group5[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "AS_GROUP6":
      return {
        ...state,
        as_group6: [
          { ...state.as_group6[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.as_group6[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.as_group6[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.as_group6[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.as_group6[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.as_group6[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.as_group6[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.as_group6[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.as_group6[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.as_group6[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.as_group6[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.as_group6[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.as_group6[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.as_group6[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.as_group6[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.as_group6[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.as_group6[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.as_group6[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.as_group6[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.as_group6[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "AS_GROUP7":
      return {
        ...state,
        as_group7: [
          { ...state.as_group7[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.as_group7[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.as_group7[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.as_group7[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.as_group7[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.as_group7[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.as_group7[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.as_group7[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.as_group7[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.as_group7[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.as_group7[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.as_group7[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.as_group7[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.as_group7[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.as_group7[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.as_group7[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.as_group7[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.as_group7[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.as_group7[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.as_group7[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "AS_GROUP8":
      return {
        ...state,
        as_group8: [
          { ...state.as_group8[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.as_group8[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.as_group8[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.as_group8[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.as_group8[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.as_group8[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.as_group8[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.as_group8[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.as_group8[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.as_group8[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.as_group8[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.as_group8[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.as_group8[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.as_group8[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.as_group8[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.as_group8[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.as_group8[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.as_group8[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.as_group8[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.as_group8[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };

    case "NA_GROUP1":
      return {
        ...state,
        na_group1: [
          { ...state.na_group1[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.na_group1[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.na_group1[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.na_group1[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.na_group1[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.na_group1[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.na_group1[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.na_group1[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.na_group1[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.na_group1[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.na_group1[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.na_group1[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.na_group1[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.na_group1[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.na_group1[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.na_group1[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.na_group1[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.na_group1[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.na_group1[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.na_group1[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "NA_GROUP2":
      return {
        ...state,
        na_group2: [
          { ...state.na_group2[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.na_group2[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.na_group2[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.na_group2[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.na_group2[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.na_group2[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.na_group2[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.na_group2[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.na_group2[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.na_group2[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.na_group2[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.na_group2[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.na_group2[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.na_group2[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.na_group2[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.na_group2[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.na_group2[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.na_group2[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.na_group2[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.na_group2[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "NA_GROUP3":
      return {
        ...state,
        na_group3: [
          { ...state.na_group3[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.na_group3[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.na_group3[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.na_group3[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.na_group3[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.na_group3[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.na_group3[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.na_group3[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.na_group3[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.na_group3[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.na_group3[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.na_group3[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.na_group3[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.na_group3[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.na_group3[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.na_group3[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.na_group3[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.na_group3[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.na_group3[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.na_group3[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "NA_GROUP4":
      return {
        ...state,
        na_group4: [
          { ...state.na_group4[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.na_group4[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.na_group4[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.na_group4[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.na_group4[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.na_group4[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.na_group4[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.na_group4[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.na_group4[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.na_group4[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.na_group4[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.na_group4[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.na_group4[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.na_group4[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.na_group4[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.na_group4[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.na_group4[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.na_group4[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.na_group4[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.na_group4[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "NA_GROUP5":
      return {
        ...state,
        na_group5: [
          { ...state.na_group5[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.na_group5[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.na_group5[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.na_group5[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.na_group5[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.na_group5[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.na_group5[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.na_group5[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.na_group5[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.na_group5[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.na_group5[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.na_group5[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.na_group5[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.na_group5[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.na_group5[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.na_group5[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.na_group5[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.na_group5[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.na_group5[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.na_group5[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "NA_GROUP6":
      return {
        ...state,
        na_group6: [
          { ...state.na_group6[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.na_group6[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.na_group6[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.na_group6[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.na_group6[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.na_group6[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.na_group6[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.na_group6[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.na_group6[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.na_group6[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.na_group6[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.na_group6[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.na_group6[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.na_group6[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.na_group6[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.na_group6[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.na_group6[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.na_group6[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.na_group6[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.na_group6[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "NA_GROUP7":
      return {
        ...state,
        na_group7: [
          { ...state.na_group7[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.na_group7[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.na_group7[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.na_group7[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.na_group7[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.na_group7[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.na_group7[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.na_group7[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.na_group7[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.na_group7[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.na_group7[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.na_group7[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.na_group7[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.na_group7[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.na_group7[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.na_group7[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.na_group7[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.na_group7[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.na_group7[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.na_group7[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    
    case "AF_GROUP1":
      return {
        ...state,
        af_group1: [
          { ...state.af_group1[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.af_group1[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.af_group1[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.af_group1[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.af_group1[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.af_group1[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.af_group1[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.af_group1[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.af_group1[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.af_group1[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.af_group1[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.af_group1[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.af_group1[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.af_group1[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.af_group1[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.af_group1[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.af_group1[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.af_group1[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.af_group1[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.af_group1[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "AF_GROUP2":
      return {
        ...state,
        af_group2: [
          { ...state.af_group2[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.af_group2[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.af_group2[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.af_group2[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.af_group2[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.af_group2[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.af_group2[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.af_group2[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.af_group2[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.af_group2[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.af_group2[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.af_group2[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.af_group2[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.af_group2[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.af_group2[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.af_group2[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.af_group2[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.af_group2[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.af_group2[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.af_group2[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "AF_GROUP3":
      return {
        ...state,
        af_group3: [
          { ...state.af_group3[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.af_group3[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.af_group3[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.af_group3[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.af_group3[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.af_group3[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.af_group3[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.af_group3[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.af_group3[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.af_group3[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.af_group3[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.af_group3[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.af_group3[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.af_group3[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.af_group3[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.af_group3[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.af_group3[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.af_group3[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.af_group3[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.af_group3[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "AF_GROUP4":
      return {
        ...state,
        af_group4: [
          { ...state.af_group4[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.af_group4[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.af_group4[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.af_group4[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.af_group4[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.af_group4[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.af_group4[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.af_group4[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.af_group4[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.af_group4[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.af_group4[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.af_group4[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.af_group4[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.af_group4[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.af_group4[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.af_group4[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.af_group4[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.af_group4[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.af_group4[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.af_group4[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "AF_GROUP5":
      return {
        ...state,
        af_group5: [
          { ...state.af_group5[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.af_group5[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.af_group5[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.af_group5[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.af_group5[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.af_group5[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.af_group5[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.af_group5[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.af_group5[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.af_group5[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.af_group5[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.af_group5[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.af_group5[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.af_group5[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.af_group5[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.af_group5[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.af_group5[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.af_group5[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.af_group5[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.af_group5[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "AF_GROUP6":
      return {
        ...state,
        af_group6: [
          { ...state.af_group6[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.af_group6[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.af_group6[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.af_group6[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.af_group6[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.af_group6[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.af_group6[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.af_group6[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.af_group6[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.af_group6[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.af_group6[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.af_group6[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.af_group6[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.af_group6[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.af_group6[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.af_group6[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.af_group6[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.af_group6[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.af_group6[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.af_group6[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "AF_GROUP7":
      return {
        ...state,
        af_group7: [
          { ...state.af_group7[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.af_group7[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.af_group7[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.af_group7[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.af_group7[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.af_group7[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.af_group7[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.af_group7[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.af_group7[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.af_group7[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.af_group7[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.af_group7[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.af_group7[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.af_group7[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.af_group7[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.af_group7[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.af_group7[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.af_group7[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.af_group7[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.af_group7[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "AF_GROUP8":
      return {
        ...state,
        af_group8: [
          { ...state.af_group8[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.af_group8[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.af_group8[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.af_group8[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.af_group8[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.af_group8[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.af_group8[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.af_group8[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.af_group8[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.af_group8[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.af_group8[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.af_group8[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.af_group8[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.af_group8[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.af_group8[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.af_group8[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.af_group8[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.af_group8[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.af_group8[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.af_group8[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "AF_GROUP9":
      return {
        ...state,
        af_group9: [
          { ...state.af_group9[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.af_group9[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.af_group9[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.af_group9[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.af_group9[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.af_group9[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.af_group9[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.af_group9[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.af_group9[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.af_group9[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.af_group9[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.af_group9[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.af_group9[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.af_group9[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.af_group9[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.af_group9[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.af_group9[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.af_group9[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.af_group9[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.af_group9[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    case "AF_GROUP10":
      return {
        ...state,
        af_group10: [
          { ...state.af_group10[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.af_group10[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.af_group10[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.af_group10[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.af_group10[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.af_group10[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.af_group10[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.af_group10[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.af_group10[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.af_group10[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.af_group10[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.af_group10[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.af_group10[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.af_group10[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.af_group10[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.af_group10[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.af_group10[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.af_group10[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.af_group10[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.af_group10[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };
    
    case "OC_GROUP1":
      return {
        ...state,
        oc_group1: [
          { ...state.oc_group1[0], teamone: ans[1], teamtwo: ans[4] },
          { ...state.oc_group1[1], teamone: ans[0], teamtwo: ans[2] },
          { ...state.oc_group1[2], teamone: ans[2], teamtwo: ans[3] },
          { ...state.oc_group1[3], teamone: ans[0], teamtwo: ans[1] },
          { ...state.oc_group1[4], teamone: ans[4], teamtwo: ans[0] },
          { ...state.oc_group1[5], teamone: ans[3], teamtwo: ans[1] },
          { ...state.oc_group1[6], teamone: ans[3], teamtwo: ans[4] },
          { ...state.oc_group1[7], teamone: ans[1], teamtwo: ans[2] },
          { ...state.oc_group1[8], teamone: ans[2], teamtwo: ans[4] },
          { ...state.oc_group1[9], teamone: ans[0], teamtwo: ans[3] },
          { ...state.oc_group1[10], teamone: ans[4], teamtwo: ans[1] },
          { ...state.oc_group1[11], teamone: ans[2], teamtwo: ans[0] },
          { ...state.oc_group1[12], teamone: ans[4], teamtwo: ans[2] },
          { ...state.oc_group1[13], teamone: ans[3], teamtwo: ans[0] },
          { ...state.oc_group1[14], teamone: ans[1], teamtwo: ans[3] },
          { ...state.oc_group1[15], teamone: ans[0], teamtwo: ans[4] },
          { ...state.oc_group1[16], teamone: ans[4], teamtwo: ans[3] },
          { ...state.oc_group1[17], teamone: ans[2], teamtwo: ans[1] },
          { ...state.oc_group1[18], teamone: ans[3], teamtwo: ans[2] },
          { ...state.oc_group1[19], teamone: ans[1], teamtwo: ans[0] },
        ],
      };

    case "ADD_SA_GAME":
      return {
        ...state,
        sa_group1: state.sa_group1.map(game),
        ...state,
        sa_group2: state.sa_group2.map(game),
      };
    case "ADD_EU_GAME":
      return {
        ...state,
        ue_group1: state.ue_group1.map(game),
        ...state,
        ue_group2: state.ue_group2.map(game),
        ...state,
        ue_group3: state.ue_group3.map(game),
        ...state,
        ue_group4: state.ue_group4.map(game),
        ...state,
        ue_group5: state.ue_group5.map(game),
        ...state,
        ue_group6: state.ue_group6.map(game),
        ...state,
        ue_group7: state.ue_group7.map(game),
        ...state,
        ue_group8: state.ue_group8.map(game),
        ...state,
        ue_group9: state.ue_group9.map(game),
        ...state,
        ue_group10: state.ue_group10.map(game),
        ...state,
        ue_group11: state.ue_group11.map(game),
      };
    case "ADD_AS_GAME":
      return {
        ...state,
        as_group1: state.as_group1.map(game),
        ...state,
        as_group2: state.as_group2.map(game),
        ...state,
        as_group3: state.as_group3.map(game),
        ...state,
        as_group4: state.as_group4.map(game),
        ...state,
        as_group5: state.as_group5.map(game),
        ...state,
        as_group6: state.as_group6.map(game),
        ...state,
        as_group7: state.as_group7.map(game),
        ...state,
        as_group8: state.as_group8.map(game),
      };
    case "ADD_NA_GAME":
      return {
        ...state,
        na_group1: state.na_group1.map(game),
        ...state,
        na_group2: state.na_group2.map(game),
        ...state,
        na_group3: state.na_group3.map(game),
        ...state,
        na_group4: state.na_group4.map(game),
        ...state,
        na_group5: state.na_group5.map(game),
        ...state,
        na_group6: state.na_group6.map(game),
        ...state,
        na_group7: state.na_group7.map(game),
      };
    case "ADD_AF_GAME":
      return {
        ...state,
        af_group1: state.af_group1.map(game),
        ...state,
        af_group2: state.af_group2.map(game),
        ...state,
        af_group3: state.af_group3.map(game),
        ...state,
        af_group4: state.af_group4.map(game),
        ...state,
        af_group5: state.af_group5.map(game),
        ...state,
        af_group6: state.af_group6.map(game),
        ...state,
        af_group7: state.af_group7.map(game),
        ...state,
        af_group8: state.af_group8.map(game),
        ...state,
        af_group9: state.af_group9.map(game),
        ...state,
        af_group10: state.af_group10.map(game),
      };
    case "ADD_OC_GAME":
      return { ...state, oc_group1: state.oc_group1.map(game) };
    
    default:
      return state;
  }
};
