const shedule = [
    {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
      {
        teamone: "",
        teamtwo: "",
        scOne: 0,
        scTwo: 0,
        endGame: false,
      },
]

const sheduleState = {
    shedule
}

export const sheduleWCReducer = (state = sheduleState, action) => {
    const ans = action.payload;
    const game = (game) => {
        if (
          game.teamone.id === ans.teamone.id &&
          game.teamtwo.id === ans.teamtwo.id
        ) {
          return {
            ...game,
            endGame: ans.endGame,
            scOne: ans.scOne,
            scTwo: ans.scTwo,
          };
        }
        return game;
      };
    switch(action.type) {
        case "GET_SHEDULE":
            return {...state, shedule: [
               {...state.shedule[0], teamone: ans[0][0], teamtwo: ans[0][1]}, 
               {...state.shedule[1], teamone: ans[0][2], teamtwo: ans[0][3]}, 
               {...state.shedule[2], teamone: ans[1][0], teamtwo: ans[1][1]}, 
               {...state.shedule[3], teamone: ans[1][2], teamtwo: ans[1][3]}, 
               {...state.shedule[4], teamone: ans[2][0], teamtwo: ans[2][1]}, 
               {...state.shedule[5], teamone: ans[2][2], teamtwo: ans[2][3]}, 
               {...state.shedule[6], teamone: ans[3][0], teamtwo: ans[3][1]}, 
               {...state.shedule[7], teamone: ans[3][2], teamtwo: ans[3][3]}, 
               {...state.shedule[8], teamone: ans[4][0], teamtwo: ans[4][1]}, 
               {...state.shedule[9], teamone: ans[4][2], teamtwo: ans[4][3]}, 
               {...state.shedule[10], teamone: ans[5][0], teamtwo: ans[5][1]}, 
               {...state.shedule[11], teamone: ans[5][2], teamtwo: ans[5][3]}, 
               {...state.shedule[12], teamone: ans[6][0], teamtwo: ans[6][1]}, 
               {...state.shedule[13], teamone: ans[6][2], teamtwo: ans[6][3]}, 
               {...state.shedule[14], teamone: ans[7][0], teamtwo: ans[7][1]}, 
               {...state.shedule[15], teamone: ans[7][2], teamtwo: ans[7][3]}, 

               {...state.shedule[16], teamone: ans[0][0], teamtwo: ans[0][2]}, 
               {...state.shedule[17], teamone: ans[0][1], teamtwo: ans[0][3]}, 
               {...state.shedule[18], teamone: ans[1][0], teamtwo: ans[1][2]}, 
               {...state.shedule[19], teamone: ans[1][1], teamtwo: ans[1][3]}, 
               {...state.shedule[20], teamone: ans[2][0], teamtwo: ans[2][2]}, 
               {...state.shedule[21], teamone: ans[2][1], teamtwo: ans[2][3]}, 
               {...state.shedule[22], teamone: ans[3][0], teamtwo: ans[3][2]}, 
               {...state.shedule[23], teamone: ans[3][1], teamtwo: ans[3][3]}, 
               {...state.shedule[24], teamone: ans[4][0], teamtwo: ans[4][2]},
               {...state.shedule[25], teamone: ans[4][1], teamtwo: ans[4][3]},
               {...state.shedule[26], teamone: ans[5][0], teamtwo: ans[5][2]},
               {...state.shedule[27], teamone: ans[5][1], teamtwo: ans[5][3]},
               {...state.shedule[28], teamone: ans[6][0], teamtwo: ans[6][2]},
               {...state.shedule[29], teamone: ans[6][1], teamtwo: ans[6][3]},
               {...state.shedule[30], teamone: ans[7][0], teamtwo: ans[7][2]},
               {...state.shedule[31], teamone: ans[7][1], teamtwo: ans[7][3]}, 

               {...state.shedule[32], teamone: ans[0][3], teamtwo: ans[0][0]},
               {...state.shedule[33], teamone: ans[0][1], teamtwo: ans[0][2]},
               {...state.shedule[34], teamone: ans[1][3], teamtwo: ans[1][0]},
               {...state.shedule[35], teamone: ans[1][1], teamtwo: ans[1][2]},
               {...state.shedule[36], teamone: ans[2][3], teamtwo: ans[2][0]},
               {...state.shedule[37], teamone: ans[2][1], teamtwo: ans[2][2]},
               {...state.shedule[38], teamone: ans[3][3], teamtwo: ans[3][0]},
               {...state.shedule[39], teamone: ans[3][1], teamtwo: ans[3][2]}, 
               {...state.shedule[40], teamone: ans[4][3], teamtwo: ans[4][0]},
               {...state.shedule[41], teamone: ans[4][1], teamtwo: ans[4][2]},
               {...state.shedule[42], teamone: ans[5][3], teamtwo: ans[5][0]},
               {...state.shedule[43], teamone: ans[5][1], teamtwo: ans[5][2]},
               {...state.shedule[44], teamone: ans[6][3], teamtwo: ans[6][0]},
               {...state.shedule[45], teamone: ans[6][1], teamtwo: ans[6][2]},
               {...state.shedule[46], teamone: ans[7][3], teamtwo: ans[7][0]},
               {...state.shedule[47], teamone: ans[7][1], teamtwo: ans[7][2]}, 
            ]}

        case "ADD_GAME":
            return {
                ...state,
                shedule: state.shedule.map(game)};    
        default:
            return state    
    }
}